services:
  - type: web
    runtime: python
    name: api
    rootDir: backend/api
    buildCommand: pip install .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  - type: web
    runtime: static
    name: frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
